### ISSUE TITLE
php8.3 support

### ISSUE THREAD

**Issue by dux-web** [stevebauman/hypertext#3]
The dependent ezyang/htmlpurifier requires 4.17.0+ to support php8.3.

Ezyang/htmlpurifier v4.16.0 requires PHP ~ 5.6.0 | | ~ 7.0.0 | | ~ 7.1.0 | | ~ 7.2.0 | | ~ 7.3.0 | | ~ 7.4.0 | | ~ 8.0.0 | | ~ 8.1.0 | | ~8.2.0 -> your php version (8.3.3) does not satisfy that requirement.

**Comment by stevebauman** [comment]
Hi @duxphp,

I'm not able to replicate this using PHP 8.3.3. Hypertext has no PHP requirement, and HtmlPurifier allows PHP 8.3:

https://github.com/ezyang/htmlpurifier/blob/bbc513d79acf6691fa9cf10f192c90dd2957f18c/composer.json#L16

Can you post your `composer.json`?

**Comment by dux-web** [comment]
I'm sorry. It's my composer mirror source.

**Comment by stevebauman** [comment]
No worries! Glad you were able to resolve it 👍
