### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by chilio** [stevebauman/hypertext#7]
@stevebauman nice package, 
Have you thought about transforming to static methods -> toText at least?

**Comment by stevebauman** [comment]
Hi @chilio, thanks.

What would static methods benefit here?

**Comment by chilio** [comment]
Hi @stevebauman,
not a biggie, but it would be shorter usage to just call `Transformer::toText($htmlData);`

**Comment by stevebauman** [comment]
Yea for sure, but you'd lose out on setting any of the available options (keep new lines, keep links, DOM filtering, etc).

You can always wrap this in your own static helper if you'd like:

```php
class HtmlToText
{
    public static function get(string $html): string
    {
        return (new Transformer)->toText($html);
    }
}
```

**Comment by chilio** [comment]
Sure, but you could then chain these specific methods also...
For example:
`Transformer::toText($htmlData)->keepNewLines()->keepLinks()`
Especially if order of these methods would not matter like in this example:
`Transformer::keepNewLines()->keepLinks()->toText($htmlData)`
Wouldn't it a little bit nicer to code?
